version: '2'

services:
  app:
    image: 'taller-2m:latest'
    container_name: taller-2m
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/tallerM2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'docker.uclv.cu/postgres'
    container_name: db
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234